// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szmcvumijszxyrktqozp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6bWN2dW1panN6eHlya3Rxb3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNjUwMTQsImV4cCI6MjA2Mjg0MTAxNH0.f85T8K837dKuX7NCAPnPIwAy5v_u_oUymPBIYtMGNUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);